### ISSUE TITLE
"Code of Conduct" section has Ukraine organizer Contact Info

### ISSUE THREAD

**Issue by anandsafi** [GDG-NewYork/devfest-nyc-2016#10]
Clicking "Code of Conduct" section in footer of the site opens up the Code of Conduct quick version page which has Ukraine organizer contact info.

Oleh Zasadnyy, +38 093 48 66 460, oleh.zasadnyy@gdg.org.ua

**Comment by gautamarora** [comment]
@nitya can you share your phone and email to be used for this page.

**Comment by nitya** [comment]
I'll reassign this to me. I don't want to put my phone on there :-) but will redirect to Slack and setup custom email for this.
