### ISSUE TITLE
"Partnership Proposition" link page in footer is broken

### ISSUE THREAD

**Issue by anandsafi** [GDG-NewYork/devfest-nyc-2016#11]
Clicking "Partnership Proposition" at bottom of page opens up http://bit.ly/devfest16-nyc-sponsor which gives a 404 "Page Not Found"

**Comment by gautamarora** [comment]
@nitya looks like a bitly url needs to be setup for this :)

**Comment by nitya** [comment]
@gautamarora done!  Fixed.
