### ISSUE TITLE
NY Times logo should be moved to the images folder

### ISSUE THREAD

**Issue by gautamarora** [GDG-NewYork/devfest-nyc-2016#23]
The NYT logo is in the root directory and does not show up on the homepage.

**Comment by gautamarora** [comment]
also, workshop.jpg should be moved to images.

**Comment by nitya** [comment]
Removed both from the base directory -- neither of those images were being used so these were accidentally added. (A lot of other cruft from original template needs to be removed as well - next!)

The NYT logo is in images/dfnyc/logo_nyt.png -- we are waiting to get sponsor feedback before we show that.  When we get confirmed, we need to just update data/partners.json to get the logo showing..
