### ISSUE TITLE
Google Analytics: Verify Setup

### ISSUE THREAD

**Issue by gautamarora** [GDG-NewYork/devfest-nyc-2016#24]
Is the page configured to use Google Analytics? I see a dns-prefetch for the google analytics domain, but there is no call to ga on page load and I cant track its usage in `https://github.com/GDG-NewYork/devfest-nyc-2016/blob/master/scripts/metrics.js` either.

This is not a `its broken` issue, but `have we set it up to work correctly` issue :)

**Comment by gautamarora** [comment]
@nitya we will need a domain setup in analytics.google.com and take the tracking code to update this line: https://github.com/GDG-NewYork/devfest-nyc-2016/blob/master/index.html#L102

**Comment by gautamarora** [comment]
@fedex1 could you help setup devfestnyc in analytics and send me the tracking id which will be of the format: `UA-XXXXXXXX-X`

**Comment by fedex1** [comment]
Here you go: UA-86211777-1

One question: what is the website link?  

The firebaseapp link is:  https://devfest-nyc-2016-9a39e.firebaseapp.com/
It appears that the custom domain seems to be devfestnyc.com and is being set up by @nitya but it is not complete.

I can change the site when devfestnyc.com is complete.

UA-86211777-1

**Comment by gautamarora** [comment]
Thanks @fedex1. Yes, the domain will be devfestnyc.com which @nitya has setup.

Fixed the tracking code https://github.com/GDG-NewYork/devfest-nyc-2016/commit/10af7475558b46870f8fd2ada39814506b6ced08
