### ISSUE TITLE
Setup custom domain for DevFest Site

### ISSUE THREAD

**Issue by nitya** [GDG-NewYork/devfest-nyc-2016#26]
Currently hosted on Firebase -- configure to use devfestnyc.com

See http://stackoverflow.com/questions/39020463/how-can-i-verify-my-custom-domain-using-domains-google-com/39020649#39020649

**Comment by nitya** [comment]
Updated records in Firebase Console. Will close this in 24 hours after verifying that the DNS records were updated and devfestnyc.com is accessible.

**Comment by gautamarora** [comment]
Its LIVE!!! 🎉

**Comment by nitya** [comment]
Verified.
