### ISSUE TITLE
Team Page (except organizers) missing Linkedin/ Twitter/ Other Social info

### ISSUE THREAD

**Issue by anandsafi** [GDG-NewYork/devfest-nyc-2016#27]
The Team page (https://devfest-nyc-2016-9a39e.firebaseapp.com/team/) is missing github/twitter/linkedin etc. - any kind of information for team members except the organizers.

**Comment by anandsafi** [comment]
Tackled through https://github.com/GDG-NewYork/devfest-nyc-2016/commit/61b75b5

**Comment by nitya** [comment]
Anand -- also need to add 
https://github.com/sreeprasad as GitHub profile for Sreeprasad

**Comment by anandsafi** [comment]
@nitya Tackled changes for Kathy, Sreeprasad and Joey through 4454fa0
You are good to go from my side of changes :)
