### ISSUE TITLE
Contact us link not clickable

### ISSUE THREAD

**Issue by fedex1** [GDG-NewYork/devfest-nyc-2016#29]
I've updated the contact us link on the https://ti.to/gdgnyc/devfest-2016 page to email sid.

See https://ti.to/gdgnyc/devfest-2016

Let me know if there is a better email address that the contact us should point to.

![contact us devfest](https://cloud.githubusercontent.com/assets/167614/19671243/5f0b4e66-9a3b-11e6-8a82-d3515e355fe1.png)

Example of what you see if you click

![screen shot 2016-10-24 at 10 52 33 pm](https://cloud.githubusercontent.com/assets/167614/19671494/22c65214-9a3d-11e6-90cf-17be6b6716ac.png)

**Comment by nitya** [comment]
Change that to sponsors@devfestnyc.com -- we should not make any person's personal email address visible on these sites (spam)

**Comment by nitya** [comment]
We have two emails we can use:
contact@ 
sponsors@

**Comment by nitya** [comment]
@fedex1 assigned this to you since you started fixing it already. Just close it when you feel its done.

**Comment by fedex1** [comment]
I set it to sponsors@  closing

**Comment by fedex1** [comment]
done.

On Mon, Oct 24, 2016 at 11:09 PM, Nitya Narasimhan <notifications@github.com
