### ISSUE TITLE
Link "BUY TICKET" in header directly to ticket sales page

### ISSUE THREAD

**Issue by nitya** [GDG-NewYork/devfest-nyc-2016#3]
Current triggers scroll down to tickets section, which then has the redirect.

**Comment by gautamarora** [comment]
looks like this has been fixed.

edit: or not, i see that you were referring to the "buy ticket" link in the hero unit and i was testing the one in the navigation header.

**Comment by gautamarora** [comment]
Fixed https://github.com/GDG-NewYork/devfest-nyc-2016/commit/3bae97a99d794ea3199d93b38f35513288567758

**Comment by gautamarora** [comment]
@karancraze sorry if you had completed this, but I am just trying to help out with the queue :)
