### ISSUE TITLE
"See link below" on ticket page is confusing

### ISSUE THREAD

**Issue by fedex1** [GDG-NewYork/devfest-nyc-2016#31]
What does see links below refer to?  see https://ti.to/gdgnyc/devfest-2016

![screen shot 2016-10-24 at 11 27 02 pm](https://cloud.githubusercontent.com/assets/167614/19672056/7e4789a6-9a41-11e6-8447-1b160144232b.png)

**Comment by nitya** [comment]
![screen shot 2016-10-24 at 11 38 29 pm](https://cloud.githubusercontent.com/assets/279083/19672286/0b0de672-9a43-11e6-8ea7-e16467e83996.png)

Fixed.

**Comment by fedex1** [comment]
Updated the page to make the "text" a link.

See https://ti.to/gdgnyc/devfest-2016 links directly to: 

https://generalassemb.ly/education/devfestnyc-ultimate-go-training/new-york-city/30237
