### ISSUE TITLE
NY Times logo for sponsors

### ISSUE THREAD

**Issue by sidwatal** [GDG-NewYork/devfest-nyc-2016#34]
![nytdevs_logo_on_transparent](https://cloud.githubusercontent.com/assets/10318340/19701975/b1b6d532-9acb-11e6-96c1-6a9570004be4.png)

Link to http://developers.nytimes.com

**Comment by gautamarora** [comment]
Fixed https://github.com/GDG-NewYork/devfest-nyc-2016/commit/315f3369b75ff0035358f4ba1563b4b2869ad4a3
