### ISSUE TITLE
"APPLY TO SPEAK AT DEVFEST NYC" link not working

### ISSUE THREAD

**Issue by anandsafi** [GDG-NewYork/devfest-nyc-2016#6]
Clicking on "APPLY TO SPEAK AT DEVFEST NYC" link does nothing at present

**Comment by fedex1** [comment]
If a link is not working, please post the actual link in the issue report

**Comment by anandsafi** [comment]
@fedex1 there seems to be no link for that currently. It it just a label with that text.

**Comment by gautamarora** [comment]
@anandsafi @fedex1 the speaker cfp section was not setup for links, it was for video players. I've updated it to work for plain old links. https://github.com/GDG-NewYork/devfest-nyc-2016/commit/526bad460626e9134a4d3298b736ccf11ce6fc86
