### ISSUE TITLE
Clicking "Continue Reading" button for "Session Track: Call for speakers" broken

### ISSUE THREAD

**Issue by anandsafi** [GDG-NewYork/devfest-nyc-2016#7]
Clicking "Continue Reading" button for "Session Track: Call for speakers" in Latest News section opens up https://devfest-nyc-2016-9a39e.firebaseapp.com/blog/posts/devfest-golang-training/ which has content for GDG DEVFEST 2015 UKRAINE

**Comment by nitya** [comment]
Fixed
