### ISSUE TITLE
Clicking "Continue Reading" button for "Hackathon Track: Call for Participation" broken

### ISSUE THREAD

**Issue by anandsafi** [GDG-NewYork/devfest-nyc-2016#8]
Clicking "Continue Reading" button for "Hackathon Track: Call for Participation" in Latest News section opens up https://devfest-nyc-2016-9a39e.firebaseapp.com/blog/posts/devfest-hackathon-cfp/ which has content for GDG DevFest Ukraine 2016 and 2015

**Comment by nitya** [comment]
Fixed
